version: '2'
services:
    worker_centos76:
        build:
          context: ./
          dockerfile: ./centos-7.6.Dockerfile
        image: noc0lour/gnuradio-buildbot-worker:centos-7.6
        container_name: worker_cos76
    worker_f30:
        build: 
          context: ./
          dockerfile: ./fedora-30.Dockerfile
        image: noc0lour/gnuradio-buildbot-worker:f30
        container_name: worker_f30
    worker_f29:
        build: 
          context: ./
          dockerfile: ./fedora-29.Dockerfile
        image: noc0lour/gnuradio-buildbot-worker:f29
        container_name: worker_f29
    worker_u1804:
        build:
          context: ./
          dockerfile: ./ubuntu-18.04.Dockerfile
        image: noc0lour/gnuradio-buildbot-worker:ubuntu-18.04
        container_name: worker_u1804
    worker_u1604:
        build:
          context: ./
          dockerfile: ./ubuntu-16.04.Dockerfile
        image: noc0lour/gnuradio-buildbot-worker:ubuntu-16.04
        container_name: worker_u1604
    worker_u1404:
        build:
          context: ./
          dockerfile: ./ubuntu-14.04.Dockerfile
        image: noc0lour/gnuradio-buildbot-worker:ubuntu-14.04
        container_name: worker_u1404
    worker_controller:
        build: 
          context: ./
          dockerfile: ./controller.Dockerfile
        image: noc0lour/gnuradio-buildbot-worker:controller
        container_name: worker_controller


